<?php
require "./includes/isAuthenticated.php";
require "./api/payments/chargeCard.php";
include_once "./includes/header.php";

include_once "./includes/helpers/main.php";

if (isset($_POST["clean-cart"])) {
    // Clears Cart
    $_SESSION["cart"] = array();
} else if (isset($_POST["process-order"])) {
    // General Data
    $chargeTotal = calculateCartTotal(); // Helper Function
    $invoiceNo = getNextOrderId(); // Helper Function

    // Card Data
    $cardNumber = $_POST["cardNumber"];
    $cvc = $_POST["cvc"];
    $expirationYear = $_POST["expirationYear"];
    $expirationMonth = $_POST["expirationMonth"];
    $expirationComposed = "{$expirationYear}-{$expirationMonth}";
    $reason = "Purchased food on Eden's Bistro";

    // User Data
    $userId = $_SESSION["userId"];
    $userData = getUserData($userId); // Helper Function

    // 1) Process Authorize
    $response = chargeCreditCard($cardNumber, $chargeTotal, $cvc, $expirationComposed, $invoiceNo, $userData, $reason);

    if (isset($response["type"]) && $response["type"] === "failed") {
        // Store Var And Output
        $result = array("type" => "FAIL");
    } else {
        // 2) Insert Into Orders Table (userId, transaction_id)
        // 3) Insert Each Item Into Order Items Using order id from prev step
        require "./includes/dbConnect.php";

        $transId = $response['transactionId'];
        $insertItemsSql = composeCartInsertString($invoiceNo);

        // Turn autocommit off
        mysqli_autocommit($conn, FALSE);

        mysqli_begin_transaction($conn);

        $insertOrder = mysqli_query($conn, "INSERT INTO orders (customer, transaction_id) VALUES ($userId, $transId)");
        $insertItems = mysqli_multi_query($conn, $insertItemsSql); // https://stackoverflow.com/questions/10924127/why-cant-i-run-two-mysqli-queries-the-second-one-fails
        while (mysqli_more_results($conn)) {
            mysqli_next_result($conn);
        } // flush multi_queries https://stackoverflow.com/questions/27899598/mysqli-multi-query-commands-out-of-sync-you-cant-run-this-command-now

        // No Need For Prepared Statements As UserId Is From Php Login 
        // & Transaction Id Is Just String Generated By chargeCard API
        if ($insertOrder and $insertItems) {
            /* commit transaction */
            if (!mysqli_commit($conn)) {
                print("Transaction commit failed\n");
                print(mysqli_error($conn));
            }

            $result = array("type" => "SUCCESS");

            // Clear Cart
            $_SESSION["cart"] = array();

            $orderProcessed = true;
        } else {
            mysqli_rollback($conn);

            // This is a problem
            $result = array("type" => "FAIL");
        }

        require "./includes/dbDisconnect.php";
    }
}
?>

<main class="main-container">
    <div class="text-center">
        <h2 class="d-inline-block" data-toggle="tooltip" data-placement="bottom" title="Click item to modify it!">Order</h2>
    </div>
    <div class="row">
        <?php
        $cart = $_SESSION["cart"];

        if (count(array_keys($cart)) === 0) {
            $cartEmpty = true;
            echo "<div class='col-12'><h5 class='my-4 text-center'>Cart is empty! Visit <a class='color-primary' href='./menu.php'>Menu!</a></h5></div>";
        } else {
            $cartEmpty = false;
            $total = 0;
            foreach ($cart as $item_id => $item_data) {
                $total += $item_data['total'];
                echo "<div class='col-sm-6'>";
                echo "<div class='card mb-3'>";
                echo "<div class='card-body order-item' onclick='modifyCart(\"SHOW\", \"$item_id\", \"{$item_data['quantity']}\");'>";
                echo "<h5 class='card-title'>{$item_data['name']} - \${$item_data['price']}</h5>";
                echo "<p class='card-text'>Ordered: {$item_data['quantity']} = Total: {$item_data['total']}</p>";
                echo "</div>";
                echo "</div>";
                echo "</div>";
            }

            echo "<div class='col-12'><h3 class='text-center my-4'>Order Total: \${$total}</h3></div>";
        }

        ?>
    </div>

    <div class="row">
        <div class="col-sm-3 offset-sm-2">
            <form class="mb-3" method="POST" action="<?php echo $_SERVER['PHP_SELF']; ?>">
                <button class="btn btn-danger btn-block" type="submit" name="clean-cart" <?php echo $cartEmpty ? 'disabled' : '' ?>>Clear Cart</button>
            </form>
        </div>
        <div class="col-sm-2"></div>
        <div class="col-sm-3">
            <button type="button" class="btn btn-site-main btn-block" data-toggle="modal" data-target="#placeOrderModal" <?php echo $cartEmpty ? 'disabled' : '' ?>>
                Make Payment
            </button>
        </div>
    </div>

    <?php
    if (isset($result) && $result['type'] === 'FAIL') {
        echo "<h5 class='text-center'>There was a problem fulfilling your request!</h5>";
        // var_dump($response);
    }
    ?>

    <div class="modal fade" id="placeOrderModal" tabindex="-1" role="dialog" aria-labelledby="placeOrderModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <form method="POST" action="<?php echo $_SERVER['PHP_SELF']; ?>">
                    <div class="modal-header">
                        <h5 class="modal-title" id="placeOrderModalLabel">Enter Payment Details</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-9">
                                <div class="form-group">
                                    <label for="cardNumber">Card Number</label>
                                    <input id="cardNumber" name="cardNumber" class="form-control" minlength="13" maxlength="19" placeholder="Ex: 5555555555554444" type="text" aria-label="Card Numbers Here" required="">
                                </div>
                            </div>
                            <div class="col-3">
                                <div class="form-group">
                                    <label for="cvc">CVC</label>
                                    <input min="100" max="999" placeholder="123" id="cvc" name="cvc" type="number" class="form-control" required=""> </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="expirationYear">Year</label>
                                    <select name="expirationYear" class="form-control" required>
                                        <?php
                                        $currentYear = date("Y"); // 2020 - 2030
                                        echo "<option selected='true' disabled='disabled'>Select a year</option>";
                                        for ($year = $currentYear + 10; $year >= $currentYear; $year--) {
                                            echo "<option value='{$year}'>{$year}</option>";
                                        }
                                        ?>
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="expirationMonth">Month</label>
                                    <select name="expirationMonth" class="form-control" required>
                                        <?php
                                        echo "<option selected='true' disabled='disabled'>Select a month</option>";
                                        $months = array("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December");
                                        foreach ($months as $idx => $month) {
                                            $mIdx = $idx + 1;
                                            echo "<option value='{$mIdx}'>{$month} - {$mIdx}</option>";
                                        }
                                        ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                        <button type="submit" name="process-order" class="btn btn-site-main">Place Order</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modifyItemModal" tabindex="-1" role="dialog" aria-labelledby="modifyItemModal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modifyItemModal">Modify Order Item</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <label for="modifyItemQty">Quantity</label>
                                <input id="modifyItemQty" name="modifyItemQty" class="form-control" type="number" min="0">
                                <input type="hidden" id="modifyItemId">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer justify-content-around">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    <button onclick="modifyCart('REMOVE');" type="button" class="btn btn-danger" data-dismiss="modal">Remove Item</button>
                    <button onclick="modifyCart('AMOUNT');" type="button" class="btn btn-site-main" data-dismiss="modal">Update Qty</button>
                </div>
            </div>
        </div>
    </div>

    <?php

    // Toggle Factory Or Not - Used For Testing
    $factoryActive = false;

    if ($factoryActive) {
        echo  "<hr>";
        echo "<h3 class='mb-3'>Factory Starts Here 😂 | Will Not Be In Production</h3>";

        require "./includes/dbConnect.php";

        $sql = "SELECT * FROM menu;";
        $result = mysqli_query($conn, $sql);

        if (mysqli_num_rows($result) > 0) {
            while ($row = mysqli_fetch_assoc($result)) {
                echo "<div class='mb-3'>";
                echo    "<h4>{$row['item_name']} - {$row['item_price']}</h4><input class='form-control w-50 d-inline-block mr-2' id='{$row['item_id']}-qty' type='number'/><button class='btn btn-site-main' onClick='addToCart({$row['item_id']})'>Add Item</button>";
                echo "</div>";
            }
        } else {
            echo "No results";
        }

        require "./includes/dbDisconnect.php";

        outputSession();
    }

    ?>
</main>
<script>
    // Activates Tooltips
    $(function() {
        $('[data-toggle="tooltip"]').tooltip()
    })

    // Alerts Successful Process
    <?php
    if (isset($orderProcessed)) {
        echo "alert('Order processed!')";
    }
    ?>
</script>

<?php
include_once "./includes/footer.php";
?>